import subprocess
import tempfile

import flask

app = flask.Flask(__name__)


def write_tempfile_and_execute_python(code):
    """
    Write the given code to a temporary file, execute it using the Python interpreter, and return the output.

    Parameters:
        code (str): The Python code to execute.

    Returns:
        str: The output generated by executing the code.
    """
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False) as temp:
        temp.write(code.encode())
        temp.flush()
        result = subprocess.run(["python", temp.name], capture_output=True, text=True)
        stdout = result.stdout
        stderr = result.stderr
        return_code = result.returncode
        output = (
            "\n=====stdout=====\n"
            + stdout
            + "\n=====stderr=====\n"
            + stderr
            + "\n=====returncode=====\n"
            + str(return_code)
        )
        return output


@app.route("/", methods=["GET"])
def index():
    return flask.render_template("index.html")


@app.route("/exec", methods=["POST"])
def api_exec():
    code = flask.request.data.decode("utf-8")
    return write_tempfile_and_execute_python(code)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=80, debug=False)
